### PR TITLE
Add German catkeys

### PR DESCRIPTION
**Pull request by humdingerb**
Here are the de.catkeys. There seem to be a few strings missing in the GUI. Try it out by changing to German in the Locale prefs. Splitting the translation of strings makes it quite difficult to get right. Hardcoding linebreaks with \n isn't ideal either... :)

I remember adding new strings being quite a PITA. you have to regenerate the en.catkeys and then find a way not to lose the de.catkeys... :)

### CODE REVIEW

**Comment by Perelandra0x309** [comment]
Awesome, thank you.  I will work on getting these added.  Yes I may tweak them bit to remove newlines or split sentences.  I also don't like how it seems to randomly order the strings in the file, it would be easier of the strings were ordered by their context.

**Comment by humdingerb** [comment]
While you're at it, you might want to consistently use sentence-casing.
There is a CatkeysEditor available that could be developed further to group strings by context. Another area would be to ease updating catkeys by only adding the new strings of the en.catkeys to the translated catkeys and updating the ID.

**Comment by Perelandra0x309** [comment]
The make file calls the collectcatkeys command which is what jumbles all the translations up when it creates the catkeys file.  I followed the source code and it is putting the catkeys into a HashMap.  Seems like the thing to do would be to sort them at the end of the collectAllCatalogKeys(BString& inputStr) function.  A good thing to put in a Trac ticket?

**Comment by humdingerb** [comment]
Go for it! Best with a patch. :)
At least it can't hurt and would make working with the catkeys in a text editor a bit better. I have added a few [issues to CatKeysEditor](https://github.com/puckipedia/BeLocalized/issues) to improve it further than that. Those should be nice GCI tasks.
If you have ideas/bugreports (for CatKeysEditor any other app hosted at some repo, like HaikuArchives, or someone's personal repo), don't hesitate to add an issue there. We can turn them into GCI tasks, too.

**Comment by Perelandra0x309** [comment]
@humdingerb 
Yes updating catkeys is a real PITA.  I am going through and eliminating \n and other things as I can.
There was one untranslated sting I found in the Launcher de.catkeys:

the length of time between the application's two most recent launches.

Do you mind translating this?  I would also like to acknowledge your contribution somewhere.

**Comment by humdingerb** [comment]
> the length of time between the application's two most recent launches.

That would be:
_dem Zeitraum zwischen den letzten beiden Starts der Anwendung._

I did that translation before... I missed to include a few corrections I did in my PR.
The rest are missing blanks at the end (which together with split strings should be avoided, generally). Maybe you can add those, all in src/Launcher/locales:
- Shorter interval will  Settings 'Apps Ranking' tab     Slider label part 1     _Kürzere Intervalle werden_ 
- Higher runtime total will      Settings 'Apps Ranking' tab     Slider label part 1     _Längere Laufzeiten werden_ 
- More
  recent dates will         Settings 'Apps Ranking' tab     Slider label part 1     _Jüngeres Datum wird_ 

> I would also like to acknowledge your contribution somewhere.

Cool, thanks! :)

**Comment by Perelandra0x309** [comment]
Thanks, I have gone through my translated strings and eliminated all spaces and \n I could and also added a few strings that were missing.  Could you check out the 3 locales in my branch v1.3.2 which are the latest and provide the newly added translations?  Also you may want to checkout my fork of BeLocalized (CatKeysEditor) and use branch "import" which I added an import function to CatKeysEditor which makes it very easy to import translations from a previous catkey file.  I also fixed the "Hide translated" option that was broken.

**Pull request merged**
